# Generated by Django 5.2.8 on 2025-11-28 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE_DUE', 'Maintenance Due'), ('OUT_OF_SERVICE', 'Out of Service')], default='OPERATIONAL', max_length=20)),
                ('operating_hours', models.FloatField(default=0.0, help_text='Total hours of operation.')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
