# Generated by Django 5.2.8 on 2025-11-28 14:49
from django.db import migrations

def seed_vehicles(apps, schema_editor):
    """
    Creates seed data for the Vehicle model.
    """
    Vehicle = apps.get_model('operations', 'Vehicle')
    
    Vehicle.objects.create(
        name='AGV-01',
        status='OPERATIONAL',
        operating_hours=125.5
    )
    Vehicle.objects.create(
        name='AGV-02',
        status='OPERATIONAL',
        operating_hours=340.2
    )
    Vehicle.objects.create(
        name='Forklift-A',
        status='MAINTENANCE_DUE',
        operating_hours=810.0
    )
    Vehicle.objects.create(
        name='Transport-C',
        status='OUT_OF_SERVICE',
        operating_hours=1500.7
    )

class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_vehicles),
    ]