# Generated by Django 5.2.8 on 2025-11-28 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_seed_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convoy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('EN_ROUTE', 'En Route'), ('IDLE', 'Idle'), ('HALTED', 'Halted')], default='IDLE', max_length=20)),
                ('current_latitude', models.FloatField()),
                ('current_longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicles', models.ManyToManyField(to='operations.vehicle')),
            ],
        ),
    ]
