# Generated by Django 5.2.8 on 2025-11-28 15:17
from django.db import migrations

def seed_convoys(apps, schema_editor):
    """
    Creates seed data for the Convoy model.
    """
    Convoy = apps.get_model('operations', 'Convoy')
    Vehicle = apps.get_model('operations', 'Vehicle')

    # Delhi: 28.6139, 77.2090
    # Mumbai: 19.0760, 72.8777

    try:
        convoy1 = Convoy.objects.create(
            name='Convoy Alpha',
            status='EN_ROUTE',
            current_latitude=27.1751, # Somewhere south of Delhi
            current_longitude=78.0421 # Agra
        )
        agv1 = Vehicle.objects.get(name='AGV-01')
        agv2 = Vehicle.objects.get(name='AGV-02')
        convoy1.vehicles.add(agv1, agv2)

        convoy2 = Convoy.objects.create(
            name='Convoy Bravo',
            status='IDLE',
            current_latitude=22.7196, # Indore
            current_longitude=75.8577
        )
        forklift = Vehicle.objects.get(name='Forklift-A')
        convoy2.vehicles.add(forklift)

    except Vehicle.DoesNotExist:
        # This might happen if the vehicle seed data was altered.
        # For a prototype, we can just skip this.
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_convoy'),
        # Ensure vehicle seed data runs before this
        ('operations', '0002_seed_vehicles'), 
    ]

    operations = [
        migrations.RunPython(seed_convoys),
    ]