# Generated by Django 5.2.8 on 2025-11-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_checkpoint_updated_at_route_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='is_comms_relay',
            field=models.BooleanField(default=False, help_text='Is this a communications relay station?'),
        ),
    ]
