# Generated by Django 5.2.8 on 2025-11-28 15:03
from django.db import migrations

def seed_checkpoints(apps, schema_editor):
    """
    Creates seed data for the Checkpoint model.
    """
    Checkpoint = apps.get_model('navigation', 'Checkpoint')

    Checkpoint.objects.create(
        name='Alpha Base',
        latitude=34.0522,
        longitude=-118.2437,
        is_comms_relay=True
    )
    Checkpoint.objects.create(
        name='Bravo Point',
        latitude=34.1522,
        longitude=-118.3437,
        is_choke_point=True
    )
    Checkpoint.objects.create(
        name='Charlie Outpost',
        latitude=34.0522,
        longitude=-118.4437,
        is_comms_relay=True
    )
    Checkpoint.objects.create(
        name='Delta Camp',
        latitude=33.9522,
        longitude=-118.2437
    )

class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_checkpoint_is_comms_relay'),
    ]

    operations = [
        migrations.RunPython(seed_checkpoints),
    ]