# Generated by Django 5.2.8 on 2025-11-28 15:15
from django.db import migrations

def update_coords_to_india(apps, schema_editor):
    """
    Updates the coordinates of existing checkpoints to cities in India.
    """
    Checkpoint = apps.get_model('navigation', 'Checkpoint')
    
    cities = {
        'Alpha Base': {'lat': 28.6139, 'lon': 77.2090},  # Delhi
        'Bravo Point': {'lat': 19.0760, 'lon': 72.8777},  # Mumbai
        'Charlie Outpost': {'lat': 12.9716, 'lon': 77.5946},  # Bengaluru
        'Delta Camp': {'lat': 22.5726, 'lon': 88.3639},   # Kolkata
    }
    
    for name, coords in cities.items():
        try:
            checkpoint = Checkpoint.objects.get(name=name)
            checkpoint.latitude = coords['lat']
            checkpoint.longitude = coords['lon']
            checkpoint.save()
        except Checkpoint.DoesNotExist:
            # In case the checkpoint was deleted or renamed, just skip.
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_seed_checkpoints'),
    ]

    operations = [
        migrations.RunPython(update_coords_to_india),
    ]