# Generated by Django 5.2.8 on 2025-11-26 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_choke_point', models.BooleanField(default=False, help_text='Is this a known traffic choke-point?')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance', models.FloatField(help_text='Total distance in kilometers.')),
                ('estimated_duration_mins', models.IntegerField(help_text='Estimated travel time in minutes without stops.')),
                ('end_checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_routes', to='navigation.checkpoint')),
                ('start_checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='navigation.checkpoint')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('distance', models.FloatField(help_text='Distance of this segment in kilometers.')),
                ('terrain_risk_score', models.IntegerField(default=0, help_text='TARI Score (0-5) based on terrain, slope, etc.')),
                ('end_checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_ends', to='navigation.checkpoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='navigation.route')),
                ('start_checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_starts', to='navigation.checkpoint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
